# FLUX Image Generator Configuration

api:
  base_url: "https://api.bfl.ai/v1"
  timeout: 300
  max_retries: 3
  retry_delay: 5
  # Оптимізовані налаштування таймауту
  polling_interval: 5         # 5 секунд між звичайними перевірками
  polling_timeout_attempts: 360  # 360 * 5s = 30 хвилин загалом
  # Налаштування модерації контенту
  moderation_timeout: 300     # 5 хвилин максимум для модерації
  moderation_interval: 3      # 3 секунди між перевірками модерації
  moderation_max_attempts: 100 # максимум спроб для модерації

generation:
  default_count: 15
  default_seed: 1000
  default_aspect_ratio: "2:3"
  default_output_format: "jpeg"
  default_quality: "high"
  default_style: "realistic" 